version: '3.1'
services:
    web:
        image: dev-odoo
        build:
            context: .
            dockerfile: dockerfile
            args:
                VERSION: 16.0
                MAXMIND_KEY: $MAXMIND_KEY
        depends_on:
            - db
        links:
            - db
        ports:
            - "8008:8008"
        volumes:
            - .odoo/session:/var/odoo/sessions
            - .odoo/filestore:/var/odoo/filestore
        #user: "skyodoo:skyodoo"
        environment:
            - INIT=base
            - ODOOPG_HOST=db
            - ODOOPG_USER=odoo
            - ODOOPG_PWD=odoo
            - DB_SSL=disable
            - ODOO_PROXY=disable
            - ODOO_DEV=all
        #command: /opt/skyant/wrapper.sh

    db:
        image: postgres:14
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-pg:/var/lib/postgresql/data/pgdata

volumes:
    odoo-pg:
